---
- name: Create monitoring namespace
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    name: monitoring
    api_version: v1
    kind: Namespace

- name: Apply K8s
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/k8s/"

- name: Appply Prometheus Operator
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/prometheus-operator/"

- name: Apply Node Exporter
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/node-exporter/"

- name: Apply armexporter
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/armexporter/"

- name: Apply kube state metrics
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/kube-state-metrics/"

- name: Apply grafana
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', './manifests/grafana/grafana-credentials.yaml') }}"

- name: Apply grafana
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/grafana/"

- name: Apply Prometheus
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/prometheus/"

- name: Apply alert manager
  k8s:
    state: present
    kubeconfig: "/etc/kubernetes/admin.conf"
    namespace: monitoring
    definition: "{{ lookup('file', '{{ item.src }}') }}"
  with_filetree: "./manifests/alertmanager/"

#- name: Apply SMTP Server
#  k8s:
#    state: present
#    kubeconfig: "/etc/kubernetes/admin.conf"
#    namespace: monitoring
#    definition: "{{ lookup('file', '{{ item.src }}') }}"
#  with_filetree: "./manifests/smtp-server/"
