---
- hosts: 127.0.0.1
  connection: local

  vars:
    username: admin
    ssh_key_path: "LaineCloud/ssh/nodes"
    hypriot_flash_version: 2.7.0
    hypriot_flash_url: "https://github.com/hypriot/flash/releases/download/{{ hypriot_flash_version }}/flash"
    hypriot_rpi_version: v1.12.1
    hypriot_rpi_url: "https://github.com/hypriot/image-builder-rpi/releases/download/{{ hypriot_rpi_version }}/hypriotos-rpi-{{ hypriot_rpi_version }}.img.zip"

  vars_prompt:
    - name: "hostname"
      prompt: "What is the name of this device"
      private: false

    - name: "device"
      prompt: "Which device should be flashed"
      default: "/dev/sda"
      private: false

  tasks:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tmp_dir

    - set_fact:
        flash_cmd: "{{ tmp_dir.path }}/flash"
        cloud_init_path: "{{ tmp_dir.path }}/cloud-init.yml"
        boot_conf_path: "{{ playbook_dir }}/files/config.txt"
        private_key_path: "{{ tmp_dir.path }}/lainecloud-nodes"
        public_key_path: "{{ tmp_dir.path }}/lainecloud-nodes.pub"

    - name: get ssh key
      command: pass LaineCloud/ssh/nodes
      register: ssh_key_raw

    - name: write ssh key
      copy:
        dest: "{{ private_key_path }}"
        content: "{{ ssh_key_raw.stdout | string | b64decode }}"

    - name: generate public key
      openssl_publickey:
        format: "OpenSSH"
        privatekey_path: "{{ private_key_path }}"
        path: "{{ public_key_path }}"

    - set_fact:
        ssh_key: "{{ lookup('file', public_key_path) }}"

    - name: download flash tool
      get_url:
        url: "{{ hypriot_flash_url }}"
        dest: "{{ tmp_dir.path }}"
        mode: a+x

    - name: create cloud init file
      template:
        src: cloud-init.yml.j2
        dest: "{{ cloud_init_path }}"

    - name: flash sd card
      command: "{{ flash_cmd }} -f -d {{ device }} -u {{ cloud_init_path }} --bootconf {{ boot_conf_path }} {{ hypriot_rpi_url }}"
      become: true
