---
- hosts: 127.0.0.1
  connection: local

  vars:
    username: admin
    ssh_key_path: "~/.ssh/lainecloud.pub"
    ssh_key: "{{ lookup('file', ssh_key_path) }}"
    image_version: v1.11.2
    image_url: "https://github.com/hypriot/image-builder-rpi/releases/download/{{ image_version }}/hypriotos-rpi-{{ image_version }}.img.zip"

  vars_prompt:
    - name: "hostname"
      prompt: "What is the name of this device"
      private: false

    - name: "device"
      prompt: "Which device should be flashed"
      default: "/dev/sdb"
      private: false

  tasks:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tmp_dir

    - name: download flash tool
      get_url:
        url: https://github.com/hypriot/flash/releases/download/2.3.0/flash
        dest: "{{ tmp_dir.path }}"
        mode: a+x

    - set_fact:
        flash_cmd: "{{ tmp_dir.path }}/flash"
        cloud_init_path: "{{ tmp_dir.path }}/cloud-init.yml"

    - name: create cloud init file
      template:
        src: cloud-init.yml.j2
        dest: "{{ cloud_init_path }}"

    - name: flash sd card
      command: "{{ flash_cmd }} -f -d {{ device }} -u {{ cloud_init_path }} {{ image_url }}"

