apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana/grafana-config.yaml
- grafana/grafana-dashboardDatasources.yaml
- grafana/grafana-dashboardDefinitions.yaml
- grafana/grafana-dashboardSources.yaml
- grafana/grafana-deployment.yaml
- grafana/grafana-ingress.yaml
- grafana/grafana-serviceAccount.yaml
- grafana/grafana-serviceMonitor.yaml
- grafana/grafana-service.yaml
- alertmanager/alertmanager-alertmanager.yaml
- alertmanager/alertmanager-ingress.yaml
- alertmanager/alertmanager-secret.yaml
- alertmanager/alertmanager-serviceAccount.yaml
- alertmanager/alertmanager-serviceMonitor.yaml
- alertmanager/alertmanager-service.yaml
- operator/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- operator/0prometheus-operator-0prometheusCustomResourceDefinition.yaml
- operator/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- operator/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- operator/0prometheus-operator-clusterRoleBinding.yaml
- operator/0prometheus-operator-clusterRole.yaml
- operator/0prometheus-operator-deployment.yaml
- operator/0prometheus-operator-serviceAccount.yaml
- operator/0prometheus-operator-serviceMonitor.yaml
- operator/0prometheus-operator-service.yaml
- exporter/node-exporter-clusterRoleBinding.yaml
- exporter/node-exporter-clusterRole.yaml
- exporter/node-exporter-daemonset.yaml
- exporter/node-exporter-serviceAccount.yaml
- exporter/node-exporter-serviceMonitor.yaml
- exporter/node-exporter-service.yaml
- kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
- kube-state-metrics/kube-state-metrics-clusterRole.yaml
- kube-state-metrics/kube-state-metrics-deployment.yaml
- kube-state-metrics/kube-state-metrics-roleBinding.yaml
- kube-state-metrics/kube-state-metrics-role.yaml
- kube-state-metrics/kube-state-metrics-serviceAccount.yaml
- kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
- kube-state-metrics/kube-state-metrics-service.yaml
- prometheus/prometheus-adapter-apiService.yaml
- prometheus/prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
- prometheus/prometheus-adapter-clusterRoleBindingDelegator.yaml
- prometheus/prometheus-adapter-clusterRoleBinding.yaml
- prometheus/prometheus-adapter-clusterRoleServerResources.yaml
- prometheus/prometheus-adapter-clusterRole.yaml
- prometheus/prometheus-adapter-configMap.yaml
- prometheus/prometheus-adapter-deployment.yaml
- prometheus/prometheus-adapter-roleBindingAuthReader.yaml
- prometheus/prometheus-adapter-serviceAccount.yaml
- prometheus/prometheus-adapter-service.yaml
- prometheus/prometheus-clusterRoleBinding.yaml
- prometheus/prometheus-clusterRole.yaml
- prometheus/prometheus-ingress.yaml
- prometheus/prometheus-kubeControllerManagerPrometheusDiscoveryService.yaml
- prometheus/prometheus-kubeDnsPrometheusDiscoveryService.yaml
- prometheus/prometheus-kubeSchedulerPrometheusDiscoveryService.yaml
- prometheus/prometheus-prometheus.yaml
- prometheus/prometheus-roleBindingConfig.yaml
- prometheus/prometheus-roleBindingSpecificNamespaces.yaml
- prometheus/prometheus-roleConfig.yaml
- prometheus/prometheus-roleSpecificNamespaces.yaml
- prometheus/prometheus-rules.yaml
- prometheus/prometheus-serviceAccount.yaml
- prometheus/prometheus-service.yaml
