---
- name: start and enable iptables
  service:
    name: iptables
    state: started
    enabled: true
  become: true

- name: flush table
  iptables:
    flush: true
  become: true

- name: prerouting interface to client ip
  iptables:
    table: nat
    chain: PREROUTING
    jump: DNAT
    in_interface: eth0
    protocol: tcp
    destination_port: 80
    to_destination: 192.168.1.240
  become: true

- name: prerouting interface to client ip
  iptables:
    table: nat
    chain: PREROUTING
    jump: DNAT
    in_interface: eth0
    protocol: tcp
    destination_port: 443
    to_destination: 192.168.1.240
  become: true

- name: masquerade tun0 interface
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: tun0
  become: true
