- name: copy easy-rsa script
  command: "cp -R /usr/share/easy-rsa/3.0.6/ /home/ec2-user/openvpn-ca"
  args:
    creates: /home/ec2-user/openvpn-ca
  become: true

- name: recursively change ownership of openvpn-ca directory
  file:
    path: /home/ec2-user/openvpn-ca
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user
  become: true

- block:
  - name: init pki
    command: ./easyrsa --batch init-pki
    args:
      chdir: ~/openvpn-ca
      creates: ~/openvpn-ca/pki

  - name: build ca
    command: ./easyrsa --batch build-ca nopass
    args:
      chdir: ~/openvpn-ca
      creates: ~/openvpn-ca/pki/ca.crt

  - name: build key server
    command: ./easyrsa --batch build-server-full server nopass
    args:
      chdir: ~/openvpn-ca
      creates: ~/openvpn-ca/pki/issued/server.crt

  - name: build dh
    command: ./easyrsa --batch gen-dh
    args:
      chdir: ~/openvpn-ca
      creates: ~/openvpn-ca/pki/dh.pem

  - name: gen hmac signature
    shell: /usr/sbin/openvpn --genkey --secret pki/ta.key
    args:
      chdir: ~/openvpn-ca
      creates: ~/openvpn-ca/pki/ta.key

- name: copy certificates and keys
  command: cp ca.crt issued/server.crt private/server.key dh.pem ta.key /etc/openvpn
  args:
    chdir: /home/ec2-user/openvpn-ca/pki
  become: true

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: true

- name: make sure log directory exists
  file:
    path: /var/log/openvpn
    state: directory
    recurse: yes
  become: true

- name: add openvpn server config file
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  become: true
