apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http-main
    port: 8080
    targetPort: http
  - name: http-self
    port: 8081
    targetPort: http
  selector:
    app: kube-state-metrics
