resources:
  - prometheus-adapter-apiService.yaml
  - prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - prometheus-adapter-clusterRoleBindingDelegator.yaml
  - prometheus-adapter-clusterRoleBinding.yaml
  - prometheus-adapter-clusterRoleServerResources.yaml
  - prometheus-adapter-clusterRole.yaml
  - prometheus-adapter-configMap.yaml
  - prometheus-adapter-deployment.yaml
  - prometheus-adapter-roleBindingAuthReader.yaml
  - prometheus-adapter-serviceAccount.yaml
  - prometheus-adapter-service.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-clusterRole.yaml
  - prometheus-ingress.yaml
  - prometheus-kubeControllerManagerPrometheusDiscoveryEndpoints.yaml
  - prometheus-kubeControllerManagerPrometheusDiscoveryService.yaml
  - prometheus-kubeDnsPrometheusDiscoveryService.yaml
  - prometheus-kubeSchedulerPrometheusDiscoveryEndpoints.yaml
  - prometheus-kubeSchedulerPrometheusDiscoveryService.yaml
  - prometheus-prometheus.yaml
  - prometheus-roleBindingConfig.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleConfig.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-rules.yaml
  - prometheus-serviceAccount.yaml
  - prometheus-serviceMonitorApiserver.yaml
  - prometheus-serviceMonitorCoreDNS.yaml
  - prometheus-serviceMonitorKubeControllerManager.yaml
  - prometheus-serviceMonitorKubelet.yaml
  - prometheus-serviceMonitorKubeScheduler.yaml
  - prometheus-serviceMonitor.yaml
  - prometheus-service.yaml
