apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    scheme: http
    port: admin
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - networking
  selector:
    matchlabels:
      k8s-app: traefik
