---
- name: create namespace
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: apply nfs provisioners
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }} "
    definition: "{{ lookup('template', '{{ item }}') }}"
    state: present
  with_items:
    - service-account.yml
    - deployment-arm.yml
    - rbac.yml
