---
- name: Install parted
  become: true
  apt:
    name: parted
    state: present

- name: Create NFS partition
  become: true
  parted:
    device: /dev/sda
    number: 1
    part_end: "85%"
    label: gpt
    state: present

- name: Create local storage partition
  become: true
  parted:
    device: /dev/sda
    number: 2
    part_start: "85%"
    label: gpt
    state: present

- name: Create a ext4 filesystem on /dev/sda1
  become: true
  filesystem:
    fstype: ext4
    dev: /dev/sda1
    opts: -cc

- name: Create a ext4 filesystem on /dev/sda2
  become: true
  filesystem:
    fstype: ext4
    dev: /dev/sda2
    opts: -cc

- name: Create nfs mount directory
  become: true
  file:
    path: /mnt/nfs
    state: directory

- name: Create data mount directory
  become: true
  file:
    path: /mnt/data
    state: directory

- name: Mount nsf partition
  become: true
  mount:
    src: /dev/sda1
    path: /mnt/nfs
    fstype: ext4
    state: mounted

- name: Mount data partition
  become: true
  mount:
    src: /dev/sda2
    path: /mnt/data
    fstype: ext4
    state: mounted

- name: Install nfs dependencies
  become: true
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present

- name: Enable nfs kernel server
  systemd:
    enabled: true
    name: nfs-kernel-server

- name: Configure nfs exports
  become: true
  lineinfile:
    path: /etc/exports
    line: "/mnt/nfs 192.168.20.1/24(rw,sync,no_subtree_check,no_root_squash)"

- name: Refresh exports
  become: true
  shell: exportfs -a
