- name: render argocd kustomization
  command: kubectl kustomize "{{ role_path }}/files"
  delegate_to: localhost
  register: manifest

- name: provision argocd
  shell: "echo {{ manifest.stdout | quote }} | {{ kubectl_cmd }} --kubeconfig {{ kubeconfig }} apply -f -"
