apiVersion: v1
kind: Namespace
metadata:
  name: status-app
  labels:
    app: status-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: status-app
  name: coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: phillebaba/test-web-server:0.1.0-alpha-linux-arm
---
apiVersion: v1
kind: Service
metadata:
  namespace: status-app
  name: coffee-svc
spec:
  selector:
    app: coffee
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: status-app
  name: test-ingress
spec:
  rules:
  - host: status.lainecloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: coffee-svc
          servicePort: 80
