- name: render metallb kustomization
  command: kubectl kustomize "{{ role_path }}/files"
  delegate_to: localhost
  register: manifest

- name: provision metallb
  shell: "echo {{ manifest.stdout | quote }} | {{ kubectl_cmd }} --kubeconfig {{ kubeconfig }} apply -f -"
