---
- name: set iptables to legacy mode
  become: true
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  register: result

- debug:
    var: result

- name: reboot machine if alternative has been updated
  become: true
  reboot:
  when: result.changed

- name: update package list
  become: true
  apt:
    update_cache: true

- name: install nfs common
  become: true
  apt:
    name: nfs-common
    state: present
