openvpn_port: 1194
openvpn_protocol: udp
openvpn_server_subnet: "172.31.0.0 255.255.0.0"
openvpn_push_route: "10.0.0.0 255.255.0.0"
openvpn_server_network: "172.31.0.0/16"

k8s_cluster_subnet: "192.168.1.0 255.255.255.0"
k8s_loadbalancer_subnet: "192.168.2.0 255.255.255.0"
k8s_public_loadbalancer:
  - ip: "192.168.2.10"
    protocol: "TCP"
    source_port: 80
    destination_port: 8000

  - ip: "192.168.2.10"
    protocol: "TCP"
    source_port: 443
    destination_port: 4443
