---
- hosts: master
  pre_tasks:
    - name: Install k8s kubectl dependencies
      become: true
      apt:
        state: present
        name:
          - build-essential
          - libssl-dev
          - libffi-dev
          - python-dev
          - python-cffi

    - name: Install pip dependencies
      become: true
      pip:
        name:
          - openshift
        state: present
  vars:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
  roles:
    - nfs
    - metrics-fix
    - networking
    - monitoring
    - status-app
