- hosts: all
  roles:
    - hypriot

- hosts:
    - storage
  gather_facts: true
  roles:
    - disk-format

- hosts:
    - master
    - worker
  roles:
    - k3s

- hosts: master
  vars:
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    kubectl_cmd: "k3s kubectl"
  roles:
    - storage-provisioner
    - metrics-server
    - metallb
    - argocd
