resources:
  - node-exporter-clusterRoleBinding.yaml
  - node-exporter-clusterRole.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-serviceAccount.yaml
  - node-exporter-serviceMonitor.yaml
  - node-exporter-service.yaml
