---
- name: Start vault container
  docker_service:
    project_name: vault
    definition:
      version: "2"
      services:
        vault:
          image: "vault:101"
          environment:
            VAULT_ADDR: http://0.0.0.0:8200
          ports:
            8200:8200
          volumes:
            - ./etc/vault.server/config:/mnt/vault/config
            - ./etc/vault.server/data:/mnt/vault/data
            - ./etc/vault.server/logs:/mnt/vault/logs
