---
- name: Check if kubeadm is init
  shell: kubeadm config view
  register: kubeadm_configured
  failed_when: kubeadm_configured.rc > 1

- name: Init kubeadm
  shell: kubeadm init --apiserver-advertise-address=192.168.20.100 
  when: kubeadm_configured.rc == 1

#- name: Install Wra
#  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/c5d10c8/Documentation/kube-flannel.yml

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command
