---
- name: Install packages for apt to use HTTPS
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Add Docker Apt signing key, will not download if present
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Get release version
  shell: lsb_release -cs
  register: release

- name: Add docker apt repository 
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian {{ release.stdout }} stable
    state: present

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
