---
- hosts: all
  become: true
  roles:
    - common

- hosts: service
  become: true
  roles:
    - nfs-server
    - vault

- hosts: masters,workers
  become: true
  roles:
    - kubeadm

- hosts: master
  become: true
  gather_facts: true
  roles:
    - k8-master
    - nfs-provisioner
    - traefik
    - k8-dashboard
    - monitoring

- hosts: workers
  become: true
  roles:
    - k8-worker
