---
- hosts: master
  become: true
  gather_facts: true
  roles:
    - kubeadm
    - role: k8-master
      tags: [k8-master]
    - role: traefik
      tags: [traefik]
    - role: k8-dashboard
      tags: [k8-dashboard]
    - role: monitoring
      tags: [monitoring]

- hosts: worker
  become: true
  roles:
    - kubeadm
    - role: k8-worker
      tags: [k8-worker]
