resources:
  - prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  - prometheus-operator-0podmonitorCustomResourceDefinition.yaml
  - prometheus-operator-0prometheusCustomResourceDefinition.yaml
  - prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  - prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
  - prometheus-operator-clusterRoleBinding.yaml
  - prometheus-operator-clusterRole.yaml
  - prometheus-operator-deployment.yaml
  - prometheus-operator-serviceAccount.yaml
  - prometheus-operator-serviceMonitor.yaml
  - prometheus-operator-service.yaml
