---
all:
  vars:
    ansible_connection: ssh
    ansible_user: pirate
  children:
    master:
      hosts:
        192.168.1.100
    worker:
      hosts:
        192.168.1.[101:105]
    nfs:
      hosts:
        192.168.1.105
