---

all:
  vars:
    ansible_connection: ssh
    ansible_user: pirate
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    master:
      hosts:
        192.168.1.100
      vars:
        hostname: "master"
    worker:
      hosts:
        192.168.1.[101:105]
      vars:
        hostname: "worker"
    nfs:
      hosts:
        192.168.1.105
