apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- github.com/danderson/metallb//manifests?ref=v0.8.3

configMapGenerator:
- name: config
  files:
  - configs/config

generatorOptions:
  disableNameSuffixHash: true
