apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/phillebaba/manifests//kube-monkey/base?ref=feature/kube-monkey
images:
  - name: ayushsobti/kube-monkey
    newName: phillebaba/kube-monkey
    newTag: latest

