---
- name: Install parted
  become: true
  apt:
    name: parted
    state: present

- name: Create NFS partition
  become: true
  parted:
    device: "{{ disk_name }}"
    number: "{{ partition_number }}"
    label: gpt
    state: present

- name: Create a ext4 filesystem on /dev/sda1
  become: true
  filesystem:
    fstype: ext4
    dev: "{{ disk_partition }}"
    opts: -cc

- name: Create nfs mount directory
  become: true
  file:
    path: "{{ mount_directory }}"
    state: directory

- name: Mount nfs partition
  become: true
  mount:
    src: "{{ disk_partition }}"
    path: "{{ mount_directory }}"
    fstype: ext4
    state: mounted
